[package]
name = "pyrays"
version = "0.1.0"
edition = "2021"

[lib]
name = "pyrays_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.5", features = ["extension-module"] }
raytrace-rs = { path = "raytrace-rs" }
